---
# CloudFormation script
# This script deploys two EC2 Linux instances, one in a public subnet and the other in a private subnet.

AWSTemplateFormatVersion:        "2010-09-09"
Description:                     Deploy EC2 instances in public and private subnets of existing non-default VPC

# Metadata:
#   template metadata
#
Parameters:

  OwnerParameter:
    Type:                        String
    Default:                     Your Name

  EnvironmentParameter:
    Type:                        String
    Default:                     dev
    AllowedValues:
    - dev
    - prod
    - test

  VpcStackNameParameter:
    Type:                        String
    Default:                     dev-vpc-stack

  EFSStackNameParameter:
    Type: String
    Default: dev-efs-stack

  EFSWebShare:
    Type: String
    Default: dev-efs-stack-WebFileShare

  KeyNameParameter:
    Description:                 Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type:                        AWS::EC2::KeyPair::KeyName
    ConstraintDescription:       Must be the name of an existing EC2 KeyPair.

  InstanceTypeParameter:
    Description:                 WebServer EC2 instance type
    Type:                        String
    Default:                     t3.micro
    AllowedValues:               [t2.nano, t2.micro, t2.small, t2.medium, t2.large, t2.xlarge, t2.2xlarge,
      t3.nano, t3.micro, t3.small, t3.medium, t3.large, t3.xlarge, t3.2xlarge,
      m4.large, m4.xlarge, m4.2xlarge, m4.4xlarge, m4.10xlarge,
      m5.large, m5.xlarge, m5.2xlarge, m5.4xlarge,
      c5.large, c5.xlarge, c5.2xlarge, c5.4xlarge, c5.9xlarge,
      g3.8xlarge,
      r5.large, r5.xlarge, r5.2xlarge, r5.4xlarge, r3.12xlarge,
      i3.xlarge, i3.2xlarge, i3.4xlarge, i3.8xlarge,
      d2.xlarge, d2.2xlarge, d2.4xlarge, d2.8xlarge]
    ConstraintDescription:       Must be a valid EC2 instance type.

  SSHLocationParameter:
    Description:                 The IP address range that can be used to SSH to the EC2 instances
    Type:                        String
    MinLength:                   9
    MaxLength:                   18
    Default:                     0.0.0.0/0
    AllowedPattern:              (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription:       Must be a valid IP CIDR range of the form x.x.x.x/x.

  LatestAmiIdParameter:
    Type:                        'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default:                     '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'





# Rules:
#   set of rules
#
# Mappings:
#   set of mappings
#
# Conditions:
#   set of conditions
#
# Transform:
#   set of transforms

Resources:

  EC2Role:
    Type:                        "AWS::IAM::Role"
    Properties:
      Description:               EC2 Role
      RoleName:                  !Join ['-',[!Ref "AWS::StackName", EC2, Role]]
      AssumeRolePolicyDocument:
        Version:                 "2012-10-17"
        Statement:
          - Effect:              "Allow"
            Principal:
              Service:
                - "ec2.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Tags:
        - Key:                   Environment
          Value:                 !Ref EnvironmentParameter


  RolePolicies:
    Type:                        "AWS::IAM::Policy"
    Properties:
      PolicyName:                "EC2-Policy"
      PolicyDocument:
        Version:                 "2012-10-17"
        Statement:
          - Effect:              "Allow"
            Action:              "*"
            Resource:            "*"
      Roles:
        - !Ref EC2Role



  LinuxServerInstanceProfile:
    Type:                        AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName:       !Join ['-', [!Ref EnvironmentParameter, LinuxServerInstanceProfile]]
      Roles:
        - !Ref EC2Role



  WebLayerSecurityGroup:
      Type:                      AWS::EC2::SecurityGroup
      Properties:
        GroupDescription:        Allow tcp traffic on port 80
        GroupName:               Port80AllTraffic
        VpcId:
          Fn::ImportValue:       !Sub "${VpcStackNameParameter}-VPCID"
        SecurityGroupIngress:
          - IpProtocol:          tcp
            FromPort:            80
            ToPort:              80
            CidrIp:              0.0.0.0/0
          - IpProtocol:          icmp
            FromPort:            8
            ToPort:              -1
            CidrIp:              0.0.0.0/0
        SecurityGroupEgress:
          - IpProtocol:          -1
            CidrIp:              0.0.0.0/0
        Tags:
          - Key:                 Environment
            Value:               !Ref EnvironmentParameter
          - Key:                 Name
            Value:               !Join ['-', [!Ref "AWS::StackName", WebLayer, Port80]]



  # Web Server(s)
  LinuxServer1:
    Type:                        AWS::EC2::Instance
    Properties:
      InstanceType:              !Ref InstanceTypeParameter
      SecurityGroupIds:
        - Fn::ImportValue:       !Sub "${VpcStackNameParameter}-DefaultSecurityGroup"
        - !Ref WebLayerSecurityGroup
      KeyName:                   !Ref KeyNameParameter
      ImageId:                   !Ref LatestAmiIdParameter
      SubnetId:
        Fn::ImportValue:         !Sub "${VpcStackNameParameter}-PublicSubnet1"
      UserData:
        !Base64 |
        #!/bin/bash
        yum update -y
        amazon-linux-extras install -y lamp-mariadb10.2-php7.2 php7.2
        yum install -y httpd
        mkdir /webshare
        mkdir /webshare/www
        mkdir /webshare/www/html
        !Sub "mount -t nfs4 -o nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport ${EFSWebShare}.efs.${AWS::Region}.amazonaws.com:/ /webshare/www/html"
        sed -i "s,/var/www/html,/webshare/www/html,g" /etc/httpd/conf/httpd.conf
        systemctl start httpd
        systemctl enable httpd
        usermod -a -G apache ec2-user
        chown -R ec2-user:apache /webshare/www/html
        chmod 2775 /webshare/www/html
        find /webshare/www/html -type d -exec chmod 2775 {} \;
        find /webshare/www/html -type f -exec chmod 0664 {} \;
        echo "<?php phpinfo(); ?>" > /webshare/www/html/phpinfo.php

        #chown -R ec2-user:apache /var/www
        #chmod 2775 /var/www
        #find /var/www -type d -exec chmod 2775 {} \;
        #find /var/www -type f -exec chmod 0664 {} \;
        #echo "<?php phpinfo(); ?>" > /var/www/html/phpinfo.php
      Tags:
        - Key:                   Environment
          Value:                 !Ref EnvironmentParameter
        - Key:                   Group
          Value:                 Web
        - Key:                   Name
          Value:                 !Join ['-', [!Ref EnvironmentParameter, LinuxWebServer1]]



Outputs:
  LinuxServerOneId:
    Description:                 InstanceId of the newly created EC2 instance
    Value:                       !Ref LinuxServer1
    Export:
      Name:                      !Join ['-', [!Ref "AWS::StackName", LinuxServerOne]]
  LinuxServerOneAZ:
    Description:                 Availability Zone of the newly created EC2 instance
    Value:                       !GetAtt [LinuxServer1, AvailabilityZone]
    Export:
      Name:                      !Join ['-', [!Ref "AWS::StackName", LinuxServerOneAZ]]
  LinuxServerOnePublicDNS:
    Description:                 Public DNSName of the newly created EC2 instance
    Value:                       !GetAtt [LinuxServer1, PublicDnsName]
    Export:
      Name:                      !Join ['-', [!Ref "AWS::StackName", LinuxServerOnePublicDNS]]
  LinuxServerOnePublicIP:
    Description:                 Public IP address of the newly created EC2 instance
    Value:                       !GetAtt [LinuxServer1, PublicIp]
    Export:
      Name:                      !Join ['-', [!Ref "AWS::StackName", LinuxServerOnePublicIP]]
